create User model
CA-G12/wms-solution-inc pull request #5
Opened 2022-10-16 09:58 UTC by sam96B

2022-10-16 10:12 UTC, AhmedSafi97 requested changes

2022-10-16 10:12 UTC, AhmedSafi97 commented on src/models/UserModel.ts
> +    modelName: 'User',
table naming should be plural all lowercase

2022-10-16 10:12 UTC, AhmedSafi97 commented on src/models/UserModel.ts
> +export class User extends Model {
leave empty lines between your code blocks

2022-10-16 10:12 UTC, AhmedSafi97 commented on src/models/UserModel.ts
> +  declare id: number
this should be creation optional

2022-10-16 15:35 UTC, AhmedSafi97 submitted a review, later dismissed
LGTM 

But we still need a slight change, I've left a comment below :pray:

2022-10-16 15:35 UTC, AhmedSafi97 commented on src/models/UserModel.ts
> +  declare role: string
Look at this comment [here](https://github.com/CA-G12/wms-solution-inc/pull/4#discussion_r996421637)

we will need the same for the `role` ['admin', 'customer']

2022-10-16 16:35 UTC, Rabee96 approved these changes

2022-10-16 20:36 UTC, ShbairAli submitted a review, later dismissed

2022-10-17 09:58 UTC, AhmedSafi97 approved these changes

2022-10-17 09:58 UTC, merged