3 backend frontend authentication flow
CA-G12/wms-solution-inc pull request #9
Opened 2022-10-18 13:29 UTC by Rabee96

2022-10-18 18:42 UTC, AhmedSafi97 requested changes

2022-10-18 18:42 UTC, AhmedSafi97 commented on src/validation/validator.ts
> +}
it is an overkill to wrap a small util in a class, 

we just need sth simple that takes the schema and data then returns the validation result!

check this example:

```js
import yup from 'yup'

export const validator = async ({
  schema,
  data
}: {
  schema: yup.ObjectSchema<any>
  data: any
}) => {
  const result = { isValid: true, error: '' }

  try {
    await schema.validate(data)
  } catch (error: unknown) {
    const validationError = error as yup.ValidationError

    result.isValid = false
    result.error = validationError.errors[0]
  }

  return result
}
```

2022-10-18 18:42 UTC, AhmedSafi97 commented on src/validation/userValidation.ts
> +const authSchema = yup.object().shape({
leave empty lines between the code blocks

2022-10-18 18:42 UTC, AhmedSafi97 commented on src/routes/UserRoute.ts
> +userRouter.post('user')
what is the point of these! your task requires only one endpoint to login users!

2022-10-18 18:42 UTC, AhmedSafi97 commented on src/routes/AuthRoute.ts
> +authRouter.post('/signup')
signup is not required at this point, please remove it

2022-10-18 18:42 UTC, AhmedSafi97 commented on src/queries/UserQuery.ts
> +export const getUserQuery = (username: string) =>
just call it `getUser` the file name tells what it is.

it should be generic and take options obj.

error should be handled by the caller so no need to wrap this in a try catch, and you should be using asyc/await anyway.

```js
const getUser = ({ filter, attributes }) => User.findOne({ where: filter, attributes, raw: true })
```

2022-10-18 18:42 UTC, AhmedSafi97 commented on src/queries/UserQuery.ts
> +export const createUserQuery = () => {
we don't need this

2022-10-18 18:42 UTC, AhmedSafi97 commented on src/models/UserModel.ts
> +  declare role: role
where did the semi colons disappear! make sure to pull the latest changes on main

2022-10-18 18:42 UTC, AhmedSafi97 commented on src/helpers/AuthHelper.ts
> +        { algorithms: ['HS256'] },
remove this, we will be using the default option

2022-10-18 18:42 UTC, AhmedSafi97 commented on src/helpers/AuthHelper.ts
> +        config.secretKey as string,
in the config set the value of `secretKey` to `|| ''` this way it will always be a string

2022-10-18 18:42 UTC, AhmedSafi97 commented on src/helpers/AuthHelper.ts
> +  create() {
create what exactly! come up with a better naming

also it should take the payload as a parameter to sign it and generate the token.

2022-10-18 18:42 UTC, AhmedSafi97 commented on src/helpers/AuthHelper.ts
> +  }
no need for the payload or the constructor here. also this be called AuthHelper!

2022-10-18 18:42 UTC, AhmedSafi97 commented on src/queries/UserQuery.ts
> +export const getUserQuery = (username: string) =>
we need to wrap this function in a class `UserQuery`

2022-10-18 18:42 UTC, AhmedSafi97 commented on src/controllers/AuthController.ts
> +  validator
use async/await

2022-10-18 18:42 UTC, AhmedSafi97 commented on src/controllers/AuthController.ts
> +  const tokenGen = new TokenGen({
this should be coming from a query! insert a dummy user into your database and make this controller generic not depending on any dummy test cases

2022-10-18 18:42 UTC, AhmedSafi97 commented on src/controllers/AuthController.ts
> +// export const createUser = () => {createUserQuery}
remove this line

2022-10-18 18:42 UTC, AhmedSafi97 commented on src/controllers/AuthController.ts
> +        return bcrypt.compare(password, user.password)
this should be in it its own function `checkPassword` and place it in the auth helper

2022-10-18 18:42 UTC, AhmedSafi97 commented on src/controllers/AuthController.ts
> +          id: user.id,
we only need the `id` in the token payload

2022-10-18 18:42 UTC, AhmedSafi97 commented on src/config/environment.ts
> +  secretKey: SECRET_KEY
`SECRET_KEY || ''` so that ts can infer that this is a string

2022-10-18 18:42 UTC, AhmedSafi97 commented on client/src/pages/AuthPage/index.tsx
> +  const [password, setPassword] = useState('')
we should be using https://react-hook-form.com/get-started#Quickstart

2022-10-18 18:42 UTC, AhmedSafi97 commented on client/src/api/auth.ts
> +    })
result and error handling should be raised up to the caller(the place where we call this function)

2022-10-18 18:42 UTC, AhmedSafi97 commented on client/src/pages/AuthPage/index.tsx
> +    signInApi({ username, password })
and what should happen when this function returns or throws and error!!

2022-10-20 09:05 UTC, ysalem-dev-89 approved these changes

2022-10-20 11:16 UTC, AhmedSafi97 approved these changes

2022-10-20 11:16 UTC, merged